apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "svc.fullname" . }}-config
  labels:
    {{- include "svc.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ .Values.config.serviceName | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  LOG_FORMAT: {{ .Values.config.logFormat | quote }}
  PORT: {{ .Values.service.targetPort | quote }}
  AUTH_SVC_URL:   {{ .Values.config.authSvcUrl   | quote }}
  FOCUS_SVC_URL:  {{ .Values.config.focusSvcUrl  | quote }}
  CARDS_SVC_URL:  {{ .Values.config.cardsSvcUrl  | quote }}
  TRILHA_SVC_URL: {{ .Values.config.trilhaSvcUrl | quote }}
