apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pickstack-cards-svc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/linuxtips/pickstack
    targetRevision: main
    path: infra/helm/charts/cards-svc
    helm:
      releaseName: pickstack
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pickstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
